version = "MatteFormer-Composition1k"
dist = false

[model]
trimap_channel = 3
mask_channel = 1
batch_size = 10
imagenet_pretrain = true
imagenet_pretrain_path = "checkpoints/best_model1k.pth"
self_refine_width1 = 30
self_refine_width2 = 15


[train]
total_step = 140000
warmup_step = 10000

val_step = 5000

clip_grad = true
G_lr = 1e-3
rec_weight = 1.0
comp_weight = 1.0
lap_weight = 1.0


[data]
train_fg = "Train/FG"
train_alpha = "Train/GT"
train_bg = "Train/BG"

test_merged = "matteformer-master/Composition-1k-testset/merged"
test_alpha = "matteformer-master/Composition-1k-testset/alpha_copy"
test_trimap = "matteformer-master/Composition-1k-testset/trimaps"

workers = 4

crop_size = 512

cutmask_prob = 0.25
augmentation = true
random_interp = true
real_world_aug = false

[log]
experiment_root = "experiments"

logging_path = "logs/stdout"
logging_step =  10
logging_level = "INFO"

checkpoint_path = "checkpoints"
checkpoint_step = 5000